
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueServiceMap", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueServiceMap {


    /**
     * 
     * @param compte
     * @throws BanqueException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "ajouterCompte", targetNamespace = "http://service/", className = "service.AjouterCompte")
    @ResponseWrapper(localName = "ajouterCompteResponse", targetNamespace = "http://service/", className = "service.AjouterCompteResponse")
    @Action(input = "http://service/BanqueServiceMap/ajouterCompteRequest", output = "http://service/BanqueServiceMap/ajouterCompteResponse", fault = {
        @FaultAction(className = BanqueException_Exception.class, value = "http://service/BanqueServiceMap/ajouterCompte/Fault/BanqueException")
    })
    public void ajouterCompte(
        @WebParam(name = "compte", targetNamespace = "")
        Compte compte)
        throws BanqueException_Exception
    ;

    /**
     * 
     * @param compte
     * @throws BanqueException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "modifierCompte", targetNamespace = "http://service/", className = "service.ModifierCompte")
    @ResponseWrapper(localName = "modifierCompteResponse", targetNamespace = "http://service/", className = "service.ModifierCompteResponse")
    @Action(input = "http://service/BanqueServiceMap/modifierCompteRequest", output = "http://service/BanqueServiceMap/modifierCompteResponse", fault = {
        @FaultAction(className = BanqueException_Exception.class, value = "http://service/BanqueServiceMap/modifierCompte/Fault/BanqueException")
    })
    public void modifierCompte(
        @WebParam(name = "compte", targetNamespace = "")
        Compte compte)
        throws BanqueException_Exception
    ;

    /**
     * 
     * @param code
     * @throws BanqueException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "supprimerCompte", targetNamespace = "http://service/", className = "service.SupprimerCompte")
    @ResponseWrapper(localName = "supprimerCompteResponse", targetNamespace = "http://service/", className = "service.SupprimerCompteResponse")
    @Action(input = "http://service/BanqueServiceMap/supprimerCompteRequest", output = "http://service/BanqueServiceMap/supprimerCompteResponse", fault = {
        @FaultAction(className = BanqueException_Exception.class, value = "http://service/BanqueServiceMap/supprimerCompte/Fault/BanqueException")
    })
    public void supprimerCompte(
        @WebParam(name = "code", targetNamespace = "")
        int code)
        throws BanqueException_Exception
    ;

    /**
     * 
     * @param mountant
     * @param code
     * @throws BanqueException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "verser", targetNamespace = "http://service/", className = "service.Verser")
    @ResponseWrapper(localName = "verserResponse", targetNamespace = "http://service/", className = "service.VerserResponse")
    @Action(input = "http://service/BanqueServiceMap/verserRequest", output = "http://service/BanqueServiceMap/verserResponse", fault = {
        @FaultAction(className = BanqueException_Exception.class, value = "http://service/BanqueServiceMap/verser/Fault/BanqueException")
    })
    public void verser(
        @WebParam(name = "code", targetNamespace = "")
        int code,
        @WebParam(name = "mountant", targetNamespace = "")
        double mountant)
        throws BanqueException_Exception
    ;

    /**
     * 
     * @param mountant
     * @param code
     * @throws BanqueException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "retirer", targetNamespace = "http://service/", className = "service.Retirer")
    @ResponseWrapper(localName = "retirerResponse", targetNamespace = "http://service/", className = "service.RetirerResponse")
    @Action(input = "http://service/BanqueServiceMap/retirerRequest", output = "http://service/BanqueServiceMap/retirerResponse", fault = {
        @FaultAction(className = BanqueException_Exception.class, value = "http://service/BanqueServiceMap/retirer/Fault/BanqueException")
    })
    public void retirer(
        @WebParam(name = "code", targetNamespace = "")
        int code,
        @WebParam(name = "mountant", targetNamespace = "")
        double mountant)
        throws BanqueException_Exception
    ;

    /**
     * 
     * @param mountant
     * @param codeDestination
     * @param codeSource
     * @throws BanqueException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "virement", targetNamespace = "http://service/", className = "service.Virement")
    @ResponseWrapper(localName = "virementResponse", targetNamespace = "http://service/", className = "service.VirementResponse")
    @Action(input = "http://service/BanqueServiceMap/virementRequest", output = "http://service/BanqueServiceMap/virementResponse", fault = {
        @FaultAction(className = BanqueException_Exception.class, value = "http://service/BanqueServiceMap/virement/Fault/BanqueException")
    })
    public void virement(
        @WebParam(name = "codeSource", targetNamespace = "")
        int codeSource,
        @WebParam(name = "codeDestination", targetNamespace = "")
        int codeDestination,
        @WebParam(name = "mountant", targetNamespace = "")
        double mountant)
        throws BanqueException_Exception
    ;

    /**
     * 
     * @param code
     * @return
     *     returns service.Compte
     * @throws BanqueException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://service/", className = "service.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://service/", className = "service.GetCompteResponse")
    @Action(input = "http://service/BanqueServiceMap/getCompteRequest", output = "http://service/BanqueServiceMap/getCompteResponse", fault = {
        @FaultAction(className = BanqueException_Exception.class, value = "http://service/BanqueServiceMap/getCompte/Fault/BanqueException")
    })
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        int code)
        throws BanqueException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<service.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://service/", className = "service.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://service/", className = "service.GetComptesResponse")
    @Action(input = "http://service/BanqueServiceMap/getComptesRequest", output = "http://service/BanqueServiceMap/getComptesResponse")
    public List<Compte> getComptes();

    /**
     * 
     * @param montant
     * @return
     *     returns double
     * @throws BanqueException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversionEuroToDH", targetNamespace = "http://service/", className = "service.ConversionEuroToDH")
    @ResponseWrapper(localName = "conversionEuroToDHResponse", targetNamespace = "http://service/", className = "service.ConversionEuroToDHResponse")
    @Action(input = "http://service/BanqueServiceMap/conversionEuroToDHRequest", output = "http://service/BanqueServiceMap/conversionEuroToDHResponse", fault = {
        @FaultAction(className = BanqueException_Exception.class, value = "http://service/BanqueServiceMap/conversionEuroToDH/Fault/BanqueException")
    })
    public double conversionEuroToDH(
        @WebParam(name = "montant", targetNamespace = "")
        double montant)
        throws BanqueException_Exception
    ;

}
