
package service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BanqueFault", targetNamespace = "http://service/")
public class BanqueException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BanqueException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BanqueException_Exception(String message, BanqueException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BanqueException_Exception(String message, BanqueException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: service.BanqueException
     */
    public BanqueException getFaultInfo() {
        return faultInfo;
    }

}
